//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QualifoodWebservicesExample.Qualifood.Webservices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatenDownloadUebersicht", Namespace="http://schemas.datacontract.org/2004/07/Qualifood.WebServices.DataContracts.Daten" +
        "Download")]
    [System.SerializableAttribute()]
    public partial class DatenDownloadUebersicht : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QualifoodWebservicesExample.Qualifood.Webservices.GattungDTO GattungField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SchlachtdatumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SchlachthofBetriebsnummerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TieranzahlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QualifoodWebservicesExample.Qualifood.Webservices.GattungDTO Gattung {
            get {
                return this.GattungField;
            }
            set {
                if ((this.GattungField.Equals(value) != true)) {
                    this.GattungField = value;
                    this.RaisePropertyChanged("Gattung");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Schlachtdatum {
            get {
                return this.SchlachtdatumField;
            }
            set {
                if ((this.SchlachtdatumField.Equals(value) != true)) {
                    this.SchlachtdatumField = value;
                    this.RaisePropertyChanged("Schlachtdatum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SchlachthofBetriebsnummer {
            get {
                return this.SchlachthofBetriebsnummerField;
            }
            set {
                if ((object.ReferenceEquals(this.SchlachthofBetriebsnummerField, value) != true)) {
                    this.SchlachthofBetriebsnummerField = value;
                    this.RaisePropertyChanged("SchlachthofBetriebsnummer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Tieranzahl {
            get {
                return this.TieranzahlField;
            }
            set {
                if ((this.TieranzahlField.Equals(value) != true)) {
                    this.TieranzahlField = value;
                    this.RaisePropertyChanged("Tieranzahl");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GattungDTO", Namespace="http://schemas.datacontract.org/2004/07/Qualifood.WebServices.DataContracts")]
    public enum GattungDTO : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Schwein = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rind = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Schaf = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SchlachtdatenSW", Namespace="http://schemas.datacontract.org/2004/07/Qualifood.WebServices.DataContracts.Schla" +
        "chtdaten")]
    [System.SerializableAttribute()]
    public partial class SchlachtdatenSW : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private QualifoodWebservicesExample.Qualifood.Webservices.SchlachtkoerperSW[] SchlachtkoerperField;
        
        private QualifoodWebservicesExample.Qualifood.Webservices.Stammdaten[] StammdatenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public QualifoodWebservicesExample.Qualifood.Webservices.SchlachtkoerperSW[] Schlachtkoerper {
            get {
                return this.SchlachtkoerperField;
            }
            set {
                if ((object.ReferenceEquals(this.SchlachtkoerperField, value) != true)) {
                    this.SchlachtkoerperField = value;
                    this.RaisePropertyChanged("Schlachtkoerper");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public QualifoodWebservicesExample.Qualifood.Webservices.Stammdaten[] Stammdaten {
            get {
                return this.StammdatenField;
            }
            set {
                if ((object.ReferenceEquals(this.StammdatenField, value) != true)) {
                    this.StammdatenField = value;
                    this.RaisePropertyChanged("Stammdaten");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SchlachtkoerperSW", Namespace="http://schemas.datacontract.org/2004/07/Qualifood.WebServices.DataContracts.Schla" +
        "chtdaten")]
    [System.SerializableAttribute()]
    public partial class SchlachtkoerperSW : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AnliefernummerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> AusgeschnittenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> AusgleichsgewichtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QualifoodWebservicesExample.Qualifood.Webservices.AutoFOM AutoFomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BakterielleUntersuchungField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BauchBewertungField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BemerkungField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BinneneberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EichspeichernummerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FerkelherkunftAufzuchtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FerkelherkunftGeburtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FreiTextVeterinaerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool GenussuntauglichField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> GeruchField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal GesamtpreisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QualifoodWebservicesExample.Qualifood.Webservices.NumerischerCode GeschlechtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HandelsklasseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HemmstoffTestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QualifoodWebservicesExample.Qualifood.Webservices.HennessyFOM HennessyFomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InterneKlasseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LaufendeNummerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> LfWertField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QualifoodWebservicesExample.Qualifood.Webservices.Betrieb LieferantField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QualifoodWebservicesExample.Qualifood.Webservices.Betrieb MastbetriebField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> NettogewichtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> PhWertField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PreisKgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PreisgruppeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QualifoodWebservicesExample.Qualifood.Webservices.NumerischerCode ProduktionsartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QualifoodWebservicesExample.Qualifood.Webservices.Betrieb ProvisionaerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QualifoodWebservicesExample.Qualifood.Webservices.NumerischerCode[] QualitaetsprogrammeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QualifoodWebservicesExample.Qualifood.Webservices.NumerischerCode SalmonellenprobenartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SalmonellenprobennummerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QualifoodWebservicesExample.Qualifood.Webservices.NumerischerCode SchlachtartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QualifoodWebservicesExample.Qualifood.Webservices.Betrieb SchlachtbetriebField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SchlachtdatumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QualifoodWebservicesExample.Qualifood.Webservices.Betrieb SchlachthofField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QualifoodWebservicesExample.Qualifood.Webservices.Betrieb SpeditionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TaetowierungField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TeilschadenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QualifoodWebservicesExample.Qualifood.Webservices.NumerischerCode[] VeterinaerbefundeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool VorlaeufigBeschlagnahmtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QualifoodWebservicesExample.Qualifood.Webservices.Merkmal[] WeitereMerkmaleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Anliefernummer {
            get {
                return this.AnliefernummerField;
            }
            set {
                if ((object.ReferenceEquals(this.AnliefernummerField, value) != true)) {
                    this.AnliefernummerField = value;
                    this.RaisePropertyChanged("Anliefernummer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Ausgeschnitten {
            get {
                return this.AusgeschnittenField;
            }
            set {
                if ((this.AusgeschnittenField.Equals(value) != true)) {
                    this.AusgeschnittenField = value;
                    this.RaisePropertyChanged("Ausgeschnitten");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Ausgleichsgewicht {
            get {
                return this.AusgleichsgewichtField;
            }
            set {
                if ((this.AusgleichsgewichtField.Equals(value) != true)) {
                    this.AusgleichsgewichtField = value;
                    this.RaisePropertyChanged("Ausgleichsgewicht");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QualifoodWebservicesExample.Qualifood.Webservices.AutoFOM AutoFom {
            get {
                return this.AutoFomField;
            }
            set {
                if ((object.ReferenceEquals(this.AutoFomField, value) != true)) {
                    this.AutoFomField = value;
                    this.RaisePropertyChanged("AutoFom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BakterielleUntersuchung {
            get {
                return this.BakterielleUntersuchungField;
            }
            set {
                if ((this.BakterielleUntersuchungField.Equals(value) != true)) {
                    this.BakterielleUntersuchungField = value;
                    this.RaisePropertyChanged("BakterielleUntersuchung");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BauchBewertung {
            get {
                return this.BauchBewertungField;
            }
            set {
                if ((object.ReferenceEquals(this.BauchBewertungField, value) != true)) {
                    this.BauchBewertungField = value;
                    this.RaisePropertyChanged("BauchBewertung");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bemerkung {
            get {
                return this.BemerkungField;
            }
            set {
                if ((object.ReferenceEquals(this.BemerkungField, value) != true)) {
                    this.BemerkungField = value;
                    this.RaisePropertyChanged("Bemerkung");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Binneneber {
            get {
                return this.BinneneberField;
            }
            set {
                if ((this.BinneneberField.Equals(value) != true)) {
                    this.BinneneberField = value;
                    this.RaisePropertyChanged("Binneneber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Eichspeichernummer {
            get {
                return this.EichspeichernummerField;
            }
            set {
                if ((object.ReferenceEquals(this.EichspeichernummerField, value) != true)) {
                    this.EichspeichernummerField = value;
                    this.RaisePropertyChanged("Eichspeichernummer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FerkelherkunftAufzucht {
            get {
                return this.FerkelherkunftAufzuchtField;
            }
            set {
                if ((object.ReferenceEquals(this.FerkelherkunftAufzuchtField, value) != true)) {
                    this.FerkelherkunftAufzuchtField = value;
                    this.RaisePropertyChanged("FerkelherkunftAufzucht");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FerkelherkunftGeburt {
            get {
                return this.FerkelherkunftGeburtField;
            }
            set {
                if ((object.ReferenceEquals(this.FerkelherkunftGeburtField, value) != true)) {
                    this.FerkelherkunftGeburtField = value;
                    this.RaisePropertyChanged("FerkelherkunftGeburt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FreiTextVeterinaer {
            get {
                return this.FreiTextVeterinaerField;
            }
            set {
                if ((object.ReferenceEquals(this.FreiTextVeterinaerField, value) != true)) {
                    this.FreiTextVeterinaerField = value;
                    this.RaisePropertyChanged("FreiTextVeterinaer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Genussuntauglich {
            get {
                return this.GenussuntauglichField;
            }
            set {
                if ((this.GenussuntauglichField.Equals(value) != true)) {
                    this.GenussuntauglichField = value;
                    this.RaisePropertyChanged("Genussuntauglich");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Geruch {
            get {
                return this.GeruchField;
            }
            set {
                if ((this.GeruchField.Equals(value) != true)) {
                    this.GeruchField = value;
                    this.RaisePropertyChanged("Geruch");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Gesamtpreis {
            get {
                return this.GesamtpreisField;
            }
            set {
                if ((this.GesamtpreisField.Equals(value) != true)) {
                    this.GesamtpreisField = value;
                    this.RaisePropertyChanged("Gesamtpreis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QualifoodWebservicesExample.Qualifood.Webservices.NumerischerCode Geschlecht {
            get {
                return this.GeschlechtField;
            }
            set {
                if ((object.ReferenceEquals(this.GeschlechtField, value) != true)) {
                    this.GeschlechtField = value;
                    this.RaisePropertyChanged("Geschlecht");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Handelsklasse {
            get {
                return this.HandelsklasseField;
            }
            set {
                if ((object.ReferenceEquals(this.HandelsklasseField, value) != true)) {
                    this.HandelsklasseField = value;
                    this.RaisePropertyChanged("Handelsklasse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HemmstoffTest {
            get {
                return this.HemmstoffTestField;
            }
            set {
                if ((this.HemmstoffTestField.Equals(value) != true)) {
                    this.HemmstoffTestField = value;
                    this.RaisePropertyChanged("HemmstoffTest");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QualifoodWebservicesExample.Qualifood.Webservices.HennessyFOM HennessyFom {
            get {
                return this.HennessyFomField;
            }
            set {
                if ((object.ReferenceEquals(this.HennessyFomField, value) != true)) {
                    this.HennessyFomField = value;
                    this.RaisePropertyChanged("HennessyFom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InterneKlasse {
            get {
                return this.InterneKlasseField;
            }
            set {
                if ((object.ReferenceEquals(this.InterneKlasseField, value) != true)) {
                    this.InterneKlasseField = value;
                    this.RaisePropertyChanged("InterneKlasse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LaufendeNummer {
            get {
                return this.LaufendeNummerField;
            }
            set {
                if ((this.LaufendeNummerField.Equals(value) != true)) {
                    this.LaufendeNummerField = value;
                    this.RaisePropertyChanged("LaufendeNummer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> LfWert {
            get {
                return this.LfWertField;
            }
            set {
                if ((this.LfWertField.Equals(value) != true)) {
                    this.LfWertField = value;
                    this.RaisePropertyChanged("LfWert");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QualifoodWebservicesExample.Qualifood.Webservices.Betrieb Lieferant {
            get {
                return this.LieferantField;
            }
            set {
                if ((object.ReferenceEquals(this.LieferantField, value) != true)) {
                    this.LieferantField = value;
                    this.RaisePropertyChanged("Lieferant");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QualifoodWebservicesExample.Qualifood.Webservices.Betrieb Mastbetrieb {
            get {
                return this.MastbetriebField;
            }
            set {
                if ((object.ReferenceEquals(this.MastbetriebField, value) != true)) {
                    this.MastbetriebField = value;
                    this.RaisePropertyChanged("Mastbetrieb");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Nettogewicht {
            get {
                return this.NettogewichtField;
            }
            set {
                if ((this.NettogewichtField.Equals(value) != true)) {
                    this.NettogewichtField = value;
                    this.RaisePropertyChanged("Nettogewicht");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> PhWert {
            get {
                return this.PhWertField;
            }
            set {
                if ((this.PhWertField.Equals(value) != true)) {
                    this.PhWertField = value;
                    this.RaisePropertyChanged("PhWert");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PreisKg {
            get {
                return this.PreisKgField;
            }
            set {
                if ((this.PreisKgField.Equals(value) != true)) {
                    this.PreisKgField = value;
                    this.RaisePropertyChanged("PreisKg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Preisgruppe {
            get {
                return this.PreisgruppeField;
            }
            set {
                if ((this.PreisgruppeField.Equals(value) != true)) {
                    this.PreisgruppeField = value;
                    this.RaisePropertyChanged("Preisgruppe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QualifoodWebservicesExample.Qualifood.Webservices.NumerischerCode Produktionsart {
            get {
                return this.ProduktionsartField;
            }
            set {
                if ((object.ReferenceEquals(this.ProduktionsartField, value) != true)) {
                    this.ProduktionsartField = value;
                    this.RaisePropertyChanged("Produktionsart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QualifoodWebservicesExample.Qualifood.Webservices.Betrieb Provisionaer {
            get {
                return this.ProvisionaerField;
            }
            set {
                if ((object.ReferenceEquals(this.ProvisionaerField, value) != true)) {
                    this.ProvisionaerField = value;
                    this.RaisePropertyChanged("Provisionaer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QualifoodWebservicesExample.Qualifood.Webservices.NumerischerCode[] Qualitaetsprogramme {
            get {
                return this.QualitaetsprogrammeField;
            }
            set {
                if ((object.ReferenceEquals(this.QualitaetsprogrammeField, value) != true)) {
                    this.QualitaetsprogrammeField = value;
                    this.RaisePropertyChanged("Qualitaetsprogramme");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QualifoodWebservicesExample.Qualifood.Webservices.NumerischerCode Salmonellenprobenart {
            get {
                return this.SalmonellenprobenartField;
            }
            set {
                if ((object.ReferenceEquals(this.SalmonellenprobenartField, value) != true)) {
                    this.SalmonellenprobenartField = value;
                    this.RaisePropertyChanged("Salmonellenprobenart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Salmonellenprobennummer {
            get {
                return this.SalmonellenprobennummerField;
            }
            set {
                if ((object.ReferenceEquals(this.SalmonellenprobennummerField, value) != true)) {
                    this.SalmonellenprobennummerField = value;
                    this.RaisePropertyChanged("Salmonellenprobennummer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QualifoodWebservicesExample.Qualifood.Webservices.NumerischerCode Schlachtart {
            get {
                return this.SchlachtartField;
            }
            set {
                if ((object.ReferenceEquals(this.SchlachtartField, value) != true)) {
                    this.SchlachtartField = value;
                    this.RaisePropertyChanged("Schlachtart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QualifoodWebservicesExample.Qualifood.Webservices.Betrieb Schlachtbetrieb {
            get {
                return this.SchlachtbetriebField;
            }
            set {
                if ((object.ReferenceEquals(this.SchlachtbetriebField, value) != true)) {
                    this.SchlachtbetriebField = value;
                    this.RaisePropertyChanged("Schlachtbetrieb");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Schlachtdatum {
            get {
                return this.SchlachtdatumField;
            }
            set {
                if ((this.SchlachtdatumField.Equals(value) != true)) {
                    this.SchlachtdatumField = value;
                    this.RaisePropertyChanged("Schlachtdatum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QualifoodWebservicesExample.Qualifood.Webservices.Betrieb Schlachthof {
            get {
                return this.SchlachthofField;
            }
            set {
                if ((object.ReferenceEquals(this.SchlachthofField, value) != true)) {
                    this.SchlachthofField = value;
                    this.RaisePropertyChanged("Schlachthof");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QualifoodWebservicesExample.Qualifood.Webservices.Betrieb Spedition {
            get {
                return this.SpeditionField;
            }
            set {
                if ((object.ReferenceEquals(this.SpeditionField, value) != true)) {
                    this.SpeditionField = value;
                    this.RaisePropertyChanged("Spedition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Taetowierung {
            get {
                return this.TaetowierungField;
            }
            set {
                if ((object.ReferenceEquals(this.TaetowierungField, value) != true)) {
                    this.TaetowierungField = value;
                    this.RaisePropertyChanged("Taetowierung");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Teilschaden {
            get {
                return this.TeilschadenField;
            }
            set {
                if ((this.TeilschadenField.Equals(value) != true)) {
                    this.TeilschadenField = value;
                    this.RaisePropertyChanged("Teilschaden");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QualifoodWebservicesExample.Qualifood.Webservices.NumerischerCode[] Veterinaerbefunde {
            get {
                return this.VeterinaerbefundeField;
            }
            set {
                if ((object.ReferenceEquals(this.VeterinaerbefundeField, value) != true)) {
                    this.VeterinaerbefundeField = value;
                    this.RaisePropertyChanged("Veterinaerbefunde");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool VorlaeufigBeschlagnahmt {
            get {
                return this.VorlaeufigBeschlagnahmtField;
            }
            set {
                if ((this.VorlaeufigBeschlagnahmtField.Equals(value) != true)) {
                    this.VorlaeufigBeschlagnahmtField = value;
                    this.RaisePropertyChanged("VorlaeufigBeschlagnahmt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QualifoodWebservicesExample.Qualifood.Webservices.Merkmal[] WeitereMerkmale {
            get {
                return this.WeitereMerkmaleField;
            }
            set {
                if ((object.ReferenceEquals(this.WeitereMerkmaleField, value) != true)) {
                    this.WeitereMerkmaleField = value;
                    this.RaisePropertyChanged("WeitereMerkmale");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Stammdaten", Namespace="http://schemas.datacontract.org/2004/07/Qualifood.WebServices.DataContracts")]
    [System.SerializableAttribute()]
    public partial class Stammdaten : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AnschriftZusatzField;
        
        private string BetriebsnummerField;
        
        private string EmailField;
        
        private string FaxField;
        
        private string HandyField;
        
        private string LandField;
        
        private string Name1Field;
        
        private string Name2Field;
        
        private string OrtField;
        
        private string PostleitzahlField;
        
        private string StrasseField;
        
        private string TelefonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string AnschriftZusatz {
            get {
                return this.AnschriftZusatzField;
            }
            set {
                if ((object.ReferenceEquals(this.AnschriftZusatzField, value) != true)) {
                    this.AnschriftZusatzField = value;
                    this.RaisePropertyChanged("AnschriftZusatz");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Betriebsnummer {
            get {
                return this.BetriebsnummerField;
            }
            set {
                if ((object.ReferenceEquals(this.BetriebsnummerField, value) != true)) {
                    this.BetriebsnummerField = value;
                    this.RaisePropertyChanged("Betriebsnummer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Fax {
            get {
                return this.FaxField;
            }
            set {
                if ((object.ReferenceEquals(this.FaxField, value) != true)) {
                    this.FaxField = value;
                    this.RaisePropertyChanged("Fax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Handy {
            get {
                return this.HandyField;
            }
            set {
                if ((object.ReferenceEquals(this.HandyField, value) != true)) {
                    this.HandyField = value;
                    this.RaisePropertyChanged("Handy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Land {
            get {
                return this.LandField;
            }
            set {
                if ((object.ReferenceEquals(this.LandField, value) != true)) {
                    this.LandField = value;
                    this.RaisePropertyChanged("Land");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Name1 {
            get {
                return this.Name1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Name1Field, value) != true)) {
                    this.Name1Field = value;
                    this.RaisePropertyChanged("Name1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Name2 {
            get {
                return this.Name2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Name2Field, value) != true)) {
                    this.Name2Field = value;
                    this.RaisePropertyChanged("Name2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Ort {
            get {
                return this.OrtField;
            }
            set {
                if ((object.ReferenceEquals(this.OrtField, value) != true)) {
                    this.OrtField = value;
                    this.RaisePropertyChanged("Ort");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Postleitzahl {
            get {
                return this.PostleitzahlField;
            }
            set {
                if ((object.ReferenceEquals(this.PostleitzahlField, value) != true)) {
                    this.PostleitzahlField = value;
                    this.RaisePropertyChanged("Postleitzahl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Strasse {
            get {
                return this.StrasseField;
            }
            set {
                if ((object.ReferenceEquals(this.StrasseField, value) != true)) {
                    this.StrasseField = value;
                    this.RaisePropertyChanged("Strasse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Telefon {
            get {
                return this.TelefonField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonField, value) != true)) {
                    this.TelefonField = value;
                    this.RaisePropertyChanged("Telefon");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AutoFOM", Namespace="http://schemas.datacontract.org/2004/07/Qualifood.WebServices.DataContracts.Daten" +
        "Download")]
    [System.SerializableAttribute()]
    public partial class AutoFOM : QualifoodWebservicesExample.Qualifood.Webservices.MesswerteSW {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> BauchgewichtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> FleischmassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> IndexpunkteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> KotelettgewichtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> LachsgewichtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> MfaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> MfaBauchField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> SchinkenSchierField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> SchinkengewichtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> Schinkenspeck1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> Schinkenspeck2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> Schinkenspeck3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> SchulterSchierField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> SchultergewichtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> SpeckmassField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Bauchgewicht {
            get {
                return this.BauchgewichtField;
            }
            set {
                if ((this.BauchgewichtField.Equals(value) != true)) {
                    this.BauchgewichtField = value;
                    this.RaisePropertyChanged("Bauchgewicht");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Fleischmass {
            get {
                return this.FleischmassField;
            }
            set {
                if ((this.FleischmassField.Equals(value) != true)) {
                    this.FleischmassField = value;
                    this.RaisePropertyChanged("Fleischmass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Indexpunkte {
            get {
                return this.IndexpunkteField;
            }
            set {
                if ((this.IndexpunkteField.Equals(value) != true)) {
                    this.IndexpunkteField = value;
                    this.RaisePropertyChanged("Indexpunkte");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Kotelettgewicht {
            get {
                return this.KotelettgewichtField;
            }
            set {
                if ((this.KotelettgewichtField.Equals(value) != true)) {
                    this.KotelettgewichtField = value;
                    this.RaisePropertyChanged("Kotelettgewicht");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Lachsgewicht {
            get {
                return this.LachsgewichtField;
            }
            set {
                if ((this.LachsgewichtField.Equals(value) != true)) {
                    this.LachsgewichtField = value;
                    this.RaisePropertyChanged("Lachsgewicht");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Mfa {
            get {
                return this.MfaField;
            }
            set {
                if ((this.MfaField.Equals(value) != true)) {
                    this.MfaField = value;
                    this.RaisePropertyChanged("Mfa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> MfaBauch {
            get {
                return this.MfaBauchField;
            }
            set {
                if ((this.MfaBauchField.Equals(value) != true)) {
                    this.MfaBauchField = value;
                    this.RaisePropertyChanged("MfaBauch");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> SchinkenSchier {
            get {
                return this.SchinkenSchierField;
            }
            set {
                if ((this.SchinkenSchierField.Equals(value) != true)) {
                    this.SchinkenSchierField = value;
                    this.RaisePropertyChanged("SchinkenSchier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Schinkengewicht {
            get {
                return this.SchinkengewichtField;
            }
            set {
                if ((this.SchinkengewichtField.Equals(value) != true)) {
                    this.SchinkengewichtField = value;
                    this.RaisePropertyChanged("Schinkengewicht");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Schinkenspeck1 {
            get {
                return this.Schinkenspeck1Field;
            }
            set {
                if ((this.Schinkenspeck1Field.Equals(value) != true)) {
                    this.Schinkenspeck1Field = value;
                    this.RaisePropertyChanged("Schinkenspeck1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Schinkenspeck2 {
            get {
                return this.Schinkenspeck2Field;
            }
            set {
                if ((this.Schinkenspeck2Field.Equals(value) != true)) {
                    this.Schinkenspeck2Field = value;
                    this.RaisePropertyChanged("Schinkenspeck2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Schinkenspeck3 {
            get {
                return this.Schinkenspeck3Field;
            }
            set {
                if ((this.Schinkenspeck3Field.Equals(value) != true)) {
                    this.Schinkenspeck3Field = value;
                    this.RaisePropertyChanged("Schinkenspeck3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> SchulterSchier {
            get {
                return this.SchulterSchierField;
            }
            set {
                if ((this.SchulterSchierField.Equals(value) != true)) {
                    this.SchulterSchierField = value;
                    this.RaisePropertyChanged("SchulterSchier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Schultergewicht {
            get {
                return this.SchultergewichtField;
            }
            set {
                if ((this.SchultergewichtField.Equals(value) != true)) {
                    this.SchultergewichtField = value;
                    this.RaisePropertyChanged("Schultergewicht");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Speckmass {
            get {
                return this.SpeckmassField;
            }
            set {
                if ((this.SpeckmassField.Equals(value) != true)) {
                    this.SpeckmassField = value;
                    this.RaisePropertyChanged("Speckmass");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NumerischerCode", Namespace="http://schemas.datacontract.org/2004/07/Qualifood.WebServices.DataContracts")]
    [System.SerializableAttribute()]
    public partial class NumerischerCode : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        private int NummerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Nummer {
            get {
                return this.NummerField;
            }
            set {
                if ((this.NummerField.Equals(value) != true)) {
                    this.NummerField = value;
                    this.RaisePropertyChanged("Nummer");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HennessyFOM", Namespace="http://schemas.datacontract.org/2004/07/Qualifood.WebServices.DataContracts.Daten" +
        "Download")]
    [System.SerializableAttribute()]
    public partial class HennessyFOM : QualifoodWebservicesExample.Qualifood.Webservices.MesswerteSW {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> FleischmassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> MfaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> ReflektionswertField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> SpeckmassField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Fleischmass {
            get {
                return this.FleischmassField;
            }
            set {
                if ((this.FleischmassField.Equals(value) != true)) {
                    this.FleischmassField = value;
                    this.RaisePropertyChanged("Fleischmass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Mfa {
            get {
                return this.MfaField;
            }
            set {
                if ((this.MfaField.Equals(value) != true)) {
                    this.MfaField = value;
                    this.RaisePropertyChanged("Mfa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Reflektionswert {
            get {
                return this.ReflektionswertField;
            }
            set {
                if ((this.ReflektionswertField.Equals(value) != true)) {
                    this.ReflektionswertField = value;
                    this.RaisePropertyChanged("Reflektionswert");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Speckmass {
            get {
                return this.SpeckmassField;
            }
            set {
                if ((this.SpeckmassField.Equals(value) != true)) {
                    this.SpeckmassField = value;
                    this.RaisePropertyChanged("Speckmass");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Betrieb", Namespace="http://schemas.datacontract.org/2004/07/Qualifood.WebServices.DataContracts")]
    [System.SerializableAttribute()]
    public partial class Betrieb : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string BetriebsnummerField;
        
        private int InterneNummerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Betriebsnummer {
            get {
                return this.BetriebsnummerField;
            }
            set {
                if ((object.ReferenceEquals(this.BetriebsnummerField, value) != true)) {
                    this.BetriebsnummerField = value;
                    this.RaisePropertyChanged("Betriebsnummer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int InterneNummer {
            get {
                return this.InterneNummerField;
            }
            set {
                if ((this.InterneNummerField.Equals(value) != true)) {
                    this.InterneNummerField = value;
                    this.RaisePropertyChanged("InterneNummer");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Merkmal", Namespace="http://schemas.datacontract.org/2004/07/Qualifood.WebServices.DataContracts")]
    [System.SerializableAttribute()]
    public partial class Merkmal : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string BezeichnungField;
        
        private string WertField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Bezeichnung {
            get {
                return this.BezeichnungField;
            }
            set {
                if ((object.ReferenceEquals(this.BezeichnungField, value) != true)) {
                    this.BezeichnungField = value;
                    this.RaisePropertyChanged("Bezeichnung");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Wert {
            get {
                return this.WertField;
            }
            set {
                if ((object.ReferenceEquals(this.WertField, value) != true)) {
                    this.WertField = value;
                    this.RaisePropertyChanged("Wert");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MesswerteSW", Namespace="http://schemas.datacontract.org/2004/07/Qualifood.WebServices.DataContracts.Daten" +
        "Download")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(QualifoodWebservicesExample.Qualifood.Webservices.HennessyFOM))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(QualifoodWebservicesExample.Qualifood.Webservices.AutoFOM))]
    public partial class MesswerteSW : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SchlachtdatenGV", Namespace="http://schemas.datacontract.org/2004/07/Qualifood.WebServices.DataContracts.Schla" +
        "chtdaten")]
    [System.SerializableAttribute()]
    public partial class SchlachtdatenGV : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private QualifoodWebservicesExample.Qualifood.Webservices.SchlachtkoerperGV[] SchlachtkoerperField;
        
        private QualifoodWebservicesExample.Qualifood.Webservices.Stammdaten[] StammdatenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public QualifoodWebservicesExample.Qualifood.Webservices.SchlachtkoerperGV[] Schlachtkoerper {
            get {
                return this.SchlachtkoerperField;
            }
            set {
                if ((object.ReferenceEquals(this.SchlachtkoerperField, value) != true)) {
                    this.SchlachtkoerperField = value;
                    this.RaisePropertyChanged("Schlachtkoerper");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public QualifoodWebservicesExample.Qualifood.Webservices.Stammdaten[] Stammdaten {
            get {
                return this.StammdatenField;
            }
            set {
                if ((object.ReferenceEquals(this.StammdatenField, value) != true)) {
                    this.StammdatenField = value;
                    this.RaisePropertyChanged("Stammdaten");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SchlachtkoerperGV", Namespace="http://schemas.datacontract.org/2004/07/Qualifood.WebServices.DataContracts.Schla" +
        "chtdaten")]
    [System.SerializableAttribute()]
    public partial class SchlachtkoerperGV : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string BemerkungKlassifiziererField;
        
        private string FettstufeField;
        
        private string GattungField;
        
        private QualifoodWebservicesExample.Qualifood.Webservices.Betrieb GeburtsbetriebField;
        
        private System.DateTime GeburtsdatumField;
        
        private string GeburtslandField;
        
        private string HandelsklasseField;
        
        private string HautfarbeField;
        
        private decimal HautgewichtField;
        
        private int HautnummerField;
        
        private int HautverschmutzungsgradField;
        
        private string HitRassenschluesselField;
        
        private string InterneKlasseField;
        
        private int LaufendeNummerField;
        
        private decimal LebendgewichtField;
        
        private QualifoodWebservicesExample.Qualifood.Webservices.Betrieb LieferantField;
        
        private QualifoodWebservicesExample.Qualifood.Webservices.Betrieb MastbetriebField;
        
        private string[] MastlaenderField;
        
        private decimal NettogewichtField;
        
        private string OhrmarkeField;
        
        private int QualitaetsprogrammSchlachthofField;
        
        private QualifoodWebservicesExample.Qualifood.Webservices.NumerischerCode[] QualitaetsprogrammeField;
        
        private decimal SchadensgewichtField;
        
        private QualifoodWebservicesExample.Qualifood.Webservices.NumerischerCode SchlachtartField;
        
        private QualifoodWebservicesExample.Qualifood.Webservices.Betrieb SchlachtbetriebField;
        
        private System.DateTime SchlachtdatumField;
        
        private QualifoodWebservicesExample.Qualifood.Webservices.Betrieb SchlachthofField;
        
        private QualifoodWebservicesExample.Qualifood.Webservices.Betrieb SpeditionField;
        
        private int VerzielungskennzeichenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QualifoodWebservicesExample.Qualifood.Webservices.NumerischerCode VeterinaerbeanstandungField;
        
        private QualifoodWebservicesExample.Qualifood.Webservices.NumerischerCode[] VeterinaerbefundeField;
        
        private string VeterinaerbemerkungField;
        
        private QualifoodWebservicesExample.Qualifood.Webservices.Merkmal[] WeitereMerkmaleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string BemerkungKlassifizierer {
            get {
                return this.BemerkungKlassifiziererField;
            }
            set {
                if ((object.ReferenceEquals(this.BemerkungKlassifiziererField, value) != true)) {
                    this.BemerkungKlassifiziererField = value;
                    this.RaisePropertyChanged("BemerkungKlassifizierer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Fettstufe {
            get {
                return this.FettstufeField;
            }
            set {
                if ((object.ReferenceEquals(this.FettstufeField, value) != true)) {
                    this.FettstufeField = value;
                    this.RaisePropertyChanged("Fettstufe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Gattung {
            get {
                return this.GattungField;
            }
            set {
                if ((object.ReferenceEquals(this.GattungField, value) != true)) {
                    this.GattungField = value;
                    this.RaisePropertyChanged("Gattung");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public QualifoodWebservicesExample.Qualifood.Webservices.Betrieb Geburtsbetrieb {
            get {
                return this.GeburtsbetriebField;
            }
            set {
                if ((object.ReferenceEquals(this.GeburtsbetriebField, value) != true)) {
                    this.GeburtsbetriebField = value;
                    this.RaisePropertyChanged("Geburtsbetrieb");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime Geburtsdatum {
            get {
                return this.GeburtsdatumField;
            }
            set {
                if ((this.GeburtsdatumField.Equals(value) != true)) {
                    this.GeburtsdatumField = value;
                    this.RaisePropertyChanged("Geburtsdatum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Geburtsland {
            get {
                return this.GeburtslandField;
            }
            set {
                if ((object.ReferenceEquals(this.GeburtslandField, value) != true)) {
                    this.GeburtslandField = value;
                    this.RaisePropertyChanged("Geburtsland");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Handelsklasse {
            get {
                return this.HandelsklasseField;
            }
            set {
                if ((object.ReferenceEquals(this.HandelsklasseField, value) != true)) {
                    this.HandelsklasseField = value;
                    this.RaisePropertyChanged("Handelsklasse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Hautfarbe {
            get {
                return this.HautfarbeField;
            }
            set {
                if ((object.ReferenceEquals(this.HautfarbeField, value) != true)) {
                    this.HautfarbeField = value;
                    this.RaisePropertyChanged("Hautfarbe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal Hautgewicht {
            get {
                return this.HautgewichtField;
            }
            set {
                if ((this.HautgewichtField.Equals(value) != true)) {
                    this.HautgewichtField = value;
                    this.RaisePropertyChanged("Hautgewicht");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Hautnummer {
            get {
                return this.HautnummerField;
            }
            set {
                if ((this.HautnummerField.Equals(value) != true)) {
                    this.HautnummerField = value;
                    this.RaisePropertyChanged("Hautnummer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Hautverschmutzungsgrad {
            get {
                return this.HautverschmutzungsgradField;
            }
            set {
                if ((this.HautverschmutzungsgradField.Equals(value) != true)) {
                    this.HautverschmutzungsgradField = value;
                    this.RaisePropertyChanged("Hautverschmutzungsgrad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string HitRassenschluessel {
            get {
                return this.HitRassenschluesselField;
            }
            set {
                if ((object.ReferenceEquals(this.HitRassenschluesselField, value) != true)) {
                    this.HitRassenschluesselField = value;
                    this.RaisePropertyChanged("HitRassenschluessel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string InterneKlasse {
            get {
                return this.InterneKlasseField;
            }
            set {
                if ((object.ReferenceEquals(this.InterneKlasseField, value) != true)) {
                    this.InterneKlasseField = value;
                    this.RaisePropertyChanged("InterneKlasse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int LaufendeNummer {
            get {
                return this.LaufendeNummerField;
            }
            set {
                if ((this.LaufendeNummerField.Equals(value) != true)) {
                    this.LaufendeNummerField = value;
                    this.RaisePropertyChanged("LaufendeNummer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal Lebendgewicht {
            get {
                return this.LebendgewichtField;
            }
            set {
                if ((this.LebendgewichtField.Equals(value) != true)) {
                    this.LebendgewichtField = value;
                    this.RaisePropertyChanged("Lebendgewicht");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public QualifoodWebservicesExample.Qualifood.Webservices.Betrieb Lieferant {
            get {
                return this.LieferantField;
            }
            set {
                if ((object.ReferenceEquals(this.LieferantField, value) != true)) {
                    this.LieferantField = value;
                    this.RaisePropertyChanged("Lieferant");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public QualifoodWebservicesExample.Qualifood.Webservices.Betrieb Mastbetrieb {
            get {
                return this.MastbetriebField;
            }
            set {
                if ((object.ReferenceEquals(this.MastbetriebField, value) != true)) {
                    this.MastbetriebField = value;
                    this.RaisePropertyChanged("Mastbetrieb");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string[] Mastlaender {
            get {
                return this.MastlaenderField;
            }
            set {
                if ((object.ReferenceEquals(this.MastlaenderField, value) != true)) {
                    this.MastlaenderField = value;
                    this.RaisePropertyChanged("Mastlaender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal Nettogewicht {
            get {
                return this.NettogewichtField;
            }
            set {
                if ((this.NettogewichtField.Equals(value) != true)) {
                    this.NettogewichtField = value;
                    this.RaisePropertyChanged("Nettogewicht");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Ohrmarke {
            get {
                return this.OhrmarkeField;
            }
            set {
                if ((object.ReferenceEquals(this.OhrmarkeField, value) != true)) {
                    this.OhrmarkeField = value;
                    this.RaisePropertyChanged("Ohrmarke");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int QualitaetsprogrammSchlachthof {
            get {
                return this.QualitaetsprogrammSchlachthofField;
            }
            set {
                if ((this.QualitaetsprogrammSchlachthofField.Equals(value) != true)) {
                    this.QualitaetsprogrammSchlachthofField = value;
                    this.RaisePropertyChanged("QualitaetsprogrammSchlachthof");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public QualifoodWebservicesExample.Qualifood.Webservices.NumerischerCode[] Qualitaetsprogramme {
            get {
                return this.QualitaetsprogrammeField;
            }
            set {
                if ((object.ReferenceEquals(this.QualitaetsprogrammeField, value) != true)) {
                    this.QualitaetsprogrammeField = value;
                    this.RaisePropertyChanged("Qualitaetsprogramme");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal Schadensgewicht {
            get {
                return this.SchadensgewichtField;
            }
            set {
                if ((this.SchadensgewichtField.Equals(value) != true)) {
                    this.SchadensgewichtField = value;
                    this.RaisePropertyChanged("Schadensgewicht");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public QualifoodWebservicesExample.Qualifood.Webservices.NumerischerCode Schlachtart {
            get {
                return this.SchlachtartField;
            }
            set {
                if ((object.ReferenceEquals(this.SchlachtartField, value) != true)) {
                    this.SchlachtartField = value;
                    this.RaisePropertyChanged("Schlachtart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public QualifoodWebservicesExample.Qualifood.Webservices.Betrieb Schlachtbetrieb {
            get {
                return this.SchlachtbetriebField;
            }
            set {
                if ((object.ReferenceEquals(this.SchlachtbetriebField, value) != true)) {
                    this.SchlachtbetriebField = value;
                    this.RaisePropertyChanged("Schlachtbetrieb");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime Schlachtdatum {
            get {
                return this.SchlachtdatumField;
            }
            set {
                if ((this.SchlachtdatumField.Equals(value) != true)) {
                    this.SchlachtdatumField = value;
                    this.RaisePropertyChanged("Schlachtdatum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public QualifoodWebservicesExample.Qualifood.Webservices.Betrieb Schlachthof {
            get {
                return this.SchlachthofField;
            }
            set {
                if ((object.ReferenceEquals(this.SchlachthofField, value) != true)) {
                    this.SchlachthofField = value;
                    this.RaisePropertyChanged("Schlachthof");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public QualifoodWebservicesExample.Qualifood.Webservices.Betrieb Spedition {
            get {
                return this.SpeditionField;
            }
            set {
                if ((object.ReferenceEquals(this.SpeditionField, value) != true)) {
                    this.SpeditionField = value;
                    this.RaisePropertyChanged("Spedition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Verzielungskennzeichen {
            get {
                return this.VerzielungskennzeichenField;
            }
            set {
                if ((this.VerzielungskennzeichenField.Equals(value) != true)) {
                    this.VerzielungskennzeichenField = value;
                    this.RaisePropertyChanged("Verzielungskennzeichen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QualifoodWebservicesExample.Qualifood.Webservices.NumerischerCode Veterinaerbeanstandung {
            get {
                return this.VeterinaerbeanstandungField;
            }
            set {
                if ((object.ReferenceEquals(this.VeterinaerbeanstandungField, value) != true)) {
                    this.VeterinaerbeanstandungField = value;
                    this.RaisePropertyChanged("Veterinaerbeanstandung");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public QualifoodWebservicesExample.Qualifood.Webservices.NumerischerCode[] Veterinaerbefunde {
            get {
                return this.VeterinaerbefundeField;
            }
            set {
                if ((object.ReferenceEquals(this.VeterinaerbefundeField, value) != true)) {
                    this.VeterinaerbefundeField = value;
                    this.RaisePropertyChanged("Veterinaerbefunde");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Veterinaerbemerkung {
            get {
                return this.VeterinaerbemerkungField;
            }
            set {
                if ((object.ReferenceEquals(this.VeterinaerbemerkungField, value) != true)) {
                    this.VeterinaerbemerkungField = value;
                    this.RaisePropertyChanged("Veterinaerbemerkung");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public QualifoodWebservicesExample.Qualifood.Webservices.Merkmal[] WeitereMerkmale {
            get {
                return this.WeitereMerkmaleField;
            }
            set {
                if ((object.ReferenceEquals(this.WeitereMerkmaleField, value) != true)) {
                    this.WeitereMerkmaleField = value;
                    this.RaisePropertyChanged("WeitereMerkmale");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Qualifood.Webservices.IDatenDownload")]
    public interface IDatenDownload {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatenDownload/GetDatenDownloadUebersicht", ReplyAction="http://tempuri.org/IDatenDownload/GetDatenDownloadUebersichtResponse")]
        QualifoodWebservicesExample.Qualifood.Webservices.DatenDownloadUebersicht[] GetDatenDownloadUebersicht(System.DateTime SchlachtdatumVon, System.DateTime SchlachtdatumBis);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatenDownload/GetDatenDownloadUebersicht", ReplyAction="http://tempuri.org/IDatenDownload/GetDatenDownloadUebersichtResponse")]
        System.Threading.Tasks.Task<QualifoodWebservicesExample.Qualifood.Webservices.DatenDownloadUebersicht[]> GetDatenDownloadUebersichtAsync(System.DateTime SchlachtdatumVon, System.DateTime SchlachtdatumBis);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatenDownload/HalloService", ReplyAction="http://tempuri.org/IDatenDownload/HalloServiceResponse")]
        string HalloService();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatenDownload/HalloService", ReplyAction="http://tempuri.org/IDatenDownload/HalloServiceResponse")]
        System.Threading.Tasks.Task<string> HalloServiceAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatenDownload/GetDatenDownloadSW", ReplyAction="http://tempuri.org/IDatenDownload/GetDatenDownloadSWResponse")]
        QualifoodWebservicesExample.Qualifood.Webservices.SchlachtdatenSW GetDatenDownloadSW(System.DateTime Schlachtdatum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatenDownload/GetDatenDownloadSW", ReplyAction="http://tempuri.org/IDatenDownload/GetDatenDownloadSWResponse")]
        System.Threading.Tasks.Task<QualifoodWebservicesExample.Qualifood.Webservices.SchlachtdatenSW> GetDatenDownloadSWAsync(System.DateTime Schlachtdatum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatenDownload/GetDatenDownloadGV", ReplyAction="http://tempuri.org/IDatenDownload/GetDatenDownloadGVResponse")]
        QualifoodWebservicesExample.Qualifood.Webservices.SchlachtdatenGV GetDatenDownloadGV(System.DateTime Schlachtdatum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatenDownload/GetDatenDownloadGV", ReplyAction="http://tempuri.org/IDatenDownload/GetDatenDownloadGVResponse")]
        System.Threading.Tasks.Task<QualifoodWebservicesExample.Qualifood.Webservices.SchlachtdatenGV> GetDatenDownloadGVAsync(System.DateTime Schlachtdatum);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDatenDownloadChannel : QualifoodWebservicesExample.Qualifood.Webservices.IDatenDownload, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DatenDownloadClient : System.ServiceModel.ClientBase<QualifoodWebservicesExample.Qualifood.Webservices.IDatenDownload>, QualifoodWebservicesExample.Qualifood.Webservices.IDatenDownload {
        
        public DatenDownloadClient() {
        }
        
        public DatenDownloadClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DatenDownloadClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DatenDownloadClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DatenDownloadClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public QualifoodWebservicesExample.Qualifood.Webservices.DatenDownloadUebersicht[] GetDatenDownloadUebersicht(System.DateTime SchlachtdatumVon, System.DateTime SchlachtdatumBis) {
            return base.Channel.GetDatenDownloadUebersicht(SchlachtdatumVon, SchlachtdatumBis);
        }
        
        public System.Threading.Tasks.Task<QualifoodWebservicesExample.Qualifood.Webservices.DatenDownloadUebersicht[]> GetDatenDownloadUebersichtAsync(System.DateTime SchlachtdatumVon, System.DateTime SchlachtdatumBis) {
            return base.Channel.GetDatenDownloadUebersichtAsync(SchlachtdatumVon, SchlachtdatumBis);
        }
        
        public string HalloService() {
            return base.Channel.HalloService();
        }
        
        public System.Threading.Tasks.Task<string> HalloServiceAsync() {
            return base.Channel.HalloServiceAsync();
        }
        
        public QualifoodWebservicesExample.Qualifood.Webservices.SchlachtdatenSW GetDatenDownloadSW(System.DateTime Schlachtdatum) {
            return base.Channel.GetDatenDownloadSW(Schlachtdatum);
        }
        
        public System.Threading.Tasks.Task<QualifoodWebservicesExample.Qualifood.Webservices.SchlachtdatenSW> GetDatenDownloadSWAsync(System.DateTime Schlachtdatum) {
            return base.Channel.GetDatenDownloadSWAsync(Schlachtdatum);
        }
        
        public QualifoodWebservicesExample.Qualifood.Webservices.SchlachtdatenGV GetDatenDownloadGV(System.DateTime Schlachtdatum) {
            return base.Channel.GetDatenDownloadGV(Schlachtdatum);
        }
        
        public System.Threading.Tasks.Task<QualifoodWebservicesExample.Qualifood.Webservices.SchlachtdatenGV> GetDatenDownloadGVAsync(System.DateTime Schlachtdatum) {
            return base.Channel.GetDatenDownloadGVAsync(Schlachtdatum);
        }
    }
}
